### ISSUE TITLE
When trying to install using the latest version of node (0.12) it fails

### ISSUE THREAD

**Issue by jlebonitte** [oransel/node-talib#18]
building talib functions...
child_process: customFds option is deprecated, use stdio instead.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/talib/src/talib.o
../src/talib.cpp:42:15: error: expected class name
class Talib : ObjectWrap {
              ^
../src/talib.cpp:92:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments& args) {
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/jlebonitte1/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/talib.cpp:331:81: error: no type named 'AccessorInfo' in namespace 'v8'
    static Handle<Value> GetFunctions(v8::Local<v8::String> property, const v8::AccessorInfo& info) {
                                                                            ~~~~^
../src/talib.cpp:378:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Explain(const Arguments& args) {
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/jlebonitte1/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/talib.cpp:394:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Execute(const Arguments& args) {
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/jlebonitte1/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/talib.cpp:846:29: error: unknown type name 'uv_work_t'
    static void ExecuteWork(uv_work_t *req) {
                            ^
../src/talib.cpp:856:33: error: unknown type name 'uv_work_t'
    static void ExecuteWorkDone(uv_work_t *req, int status) {
                                ^
../src/talib.cpp:71:21: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/jlebonitte1/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/talib.cpp:72:81: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value>
      (const v8::internal::Arguments &)'
        Local<FunctionTemplate> local_function_template = FunctionTemplate::New(New);
                                                                                ^~~
/Users/jlebonitte1/.node-gyp/0.12.0/deps/v8/include/v8.h:3456:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../src/talib.cpp:73:70: error: 'New' is a private member of 'v8::PersistentBase<v8::FunctionTemplate>'
        persistent_function_template = Persistent<FunctionTemplate>::New(local_function_template);
                                                                     ^
/Users/jlebonitte1/.node-gyp/0.12.0/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/talib.cpp:73:40: error: too few arguments to function call, expected 2, have 1; did you mean '::Talib::New'?
        persistent_function_template = Persistent<FunctionTemplate>::New(local_function_template);
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                       ::Talib::New
../src/talib.cpp:92:26: note: '::Talib::New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/talib.cpp:74:37: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use
      '.'?
        persistent_function_template->InstanceTemplate()->SetInternalFieldCount(1);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                                    .
../src/talib.cpp:74:39: error: no member named 'InstanceTemplate' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
        persistent_function_template->InstanceTemplate()->SetInternalFieldCount(1);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../src/talib.cpp:75:37: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use
      '.'?
        persistent_function_template->SetClassName(String::NewSymbol("TALib"));
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                                    .
../src/talib.cpp:75:39: error: no member named 'SetClassName' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
        persistent_function_template->SetClassName(String::NewSymbol("TALib"));
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../src/talib.cpp:75:60: error: no member named 'NewSymbol' in 'v8::String'
        persistent_function_template->SetClassName(String::NewSymbol("TALib"));
                                                   ~~~~~~~~^
../src/talib.cpp:78:21: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
        target->Set(String::New("version"), String::New("0.4.2"));
                    ^~~~~~~~~~~
                    New
../src/talib.cpp:92:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/talib.cpp:78:33: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type
      'const char [8]'
        target->Set(String::New("version"), String::New("0.4.2"));
                                ^~~~~~~~~
../src/talib.cpp:92:47: note: passing argument to parameter 'args' here
    static Handle<Value> New(const Arguments& args) {
                                              ^
../src/talib.cpp:81:29: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
        target->SetAccessor(String::New("functions"), GetFunctions, NULL);
                            ^~~~~~~~~~~
                            New
../src/talib.cpp:92:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/talib/src/talib.o] Error 1

**Comment by oransel** [comment]
Sorry, please use 0.10 for now. Working on supporting 0.12.

**Comment by oransel** [comment]
please test 8329de99b41bed3d2ed6994624e0eb8697051fcb

**Comment by jlebonitte** [comment]
Will test in the morning.  Thanks for the quick response!
Jim Lebonitte

CTO | alta5 <http://alta5.com/>
Cell: (813) 992-6437

jim@alta5.com <mailto:jim@alta5.com> 

 <http://www.alta5.com/>

**Comment by jlebonitte** [comment]
This seems to be working for us.  The install is working and our app is now running kind of as expected.  I am having other .12 issues unrelated to you guys.  

How long until this will be moved into an npm version?

Thanks Again!
Jim Lebonitte

CTO | alta5 <http://alta5.com/>
Cell: (813) 992-6437

jim@alta5.com <mailto:jim@alta5.com> 

 <http://www.alta5.com/>

**Comment by oransel** [comment]
Waiting on a few more people testing. It should be released soon.

**Comment by oransel** [comment]
fix is released https://github.com/oransel/node-talib/releases/tag/v0.5.0
